_target_: diffusion_planner.models.diffusion_planner.DiffusionPlanner
hidden_dim: 256
num_heads: 8
scene_fusion_depth: 4
element_encoder_depth: 2
decoder_depth: 6
trajectory_encoder_depth: 2
feedforward_dim: 1024
embed_dim: 128
drop_path_rate: 0.0
dropout: 0.0
velocity_threshold: 0.1
time_mean: -0.4
time_std: 1.0
time_epsilon: 1.0e-5
noise_scale: 1.0
position_scale: 50.0
speed_scale: 15.0
vehicle_shape_scale: 10.0
