#!/bin/bash
# Run token analyses and build a self-contained HTML report.
#
# The model dir must contain args.json + best_model.pth.
# The normalizer is read from the model's args.json, so no local training config
# is needed.
#
# Data: set DATADIR to a dataset root. If $DATADIR/path_list_valid.json does not
# exist, a path list is auto-generated by recursively globbing *.npz (note: this
# mixes train/valid if the directory contains both; pass VALID_LIST explicitly
# to use a specific split).
#
# Usage (from repo root on A100):
#   ./run_token_analysis.sh
#   DATADIR=/home/yamashita/work_hdd/sample/il_odaiba_shinagawa_j6_npz \
#     N_SAMPLES=1024 BATCH_SIZE=64 ./run_token_analysis.sh
#
# Outputs:
#   token_importance_n<N>.tsv
#   attention_n<N>.json
#   token_analysis_n<N>.executed.ipynb
#   token_analysis_n<N>.html  (single-file, embedded images)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

MODEL_DIR="${MODEL_DIR:-$REPO_ROOT/best_models/20260730/best_model}"
DATADIR="${DATADIR:-/home/yamashita/work_hdd/sample/mini_datasets/j6_2231_fullseq_mini_20260707}"
N="${N_SAMPLES:-128}"
BS="${BATCH_SIZE:-32}"
DEVICE="${DEVICE:-cuda}"
MOVE_MIN_M="${MOVE_MIN_M:-5.0}"
TURN_DEG="${TURN_DEG:-15.0}"
TAG="$(basename "$DATADIR")"
OUT="${OUT_DIR:-$MODEL_DIR/../eval_${TAG}}"
PYTHON_BIN="${PYTHON_BIN:-$REPO_ROOT/.venv/bin/python}"

mkdir -p "$OUT"
OUT="$(cd "$OUT" && pwd)"
MODEL_DIR="$(cd "$MODEL_DIR" && pwd)"
export PYTHONUNBUFFERED=1
export MPLCONFIGDIR="${MPLCONFIGDIR:-$OUT/.matplotlib}"
mkdir -p "$MPLCONFIGDIR"

if [ ! -x "$PYTHON_BIN" ]; then
  echo "Python not found or not executable: $PYTHON_BIN" >&2
  exit 1
fi

if ! "$PYTHON_BIN" -c "import nbconvert, ipykernel" >/dev/null 2>&1; then
  cat >&2 <<EOF
Notebook report dependencies are missing from:
  $PYTHON_BIN

Install them once with:
  UV_CACHE_DIR=/tmp/diffusion-planner-uv-cache \
    uv pip install --python "$PYTHON_BIN" nbconvert ipykernel
EOF
  exit 1
fi

VALID_LIST="${VALID_LIST:-$DATADIR/path_list_valid.json}"
if [ ! -f "$VALID_LIST" ]; then
  VALID_LIST="$OUT/path_list_all.json"
  echo "=== no path_list_valid.json in $DATADIR -> globbing *.npz into $VALID_LIST ==="
  "$PYTHON_BIN" - "$DATADIR" "$VALID_LIST" <<'PY'
import glob
import json
import sys

files = sorted(glob.glob(sys.argv[1] + "/**/*.npz", recursive=True))
assert files, f"no npz found under {sys.argv[1]}"
with open(sys.argv[2], "w") as f:
    json.dump(files, f)
print(f"{len(files)} npz -> {sys.argv[2]}")
PY
fi
VALID_LIST="$(cd "$(dirname "$VALID_LIST")" && pwd)/$(basename "$VALID_LIST")"

echo "=== [1/3] token importance (PyTorch, $DEVICE, n=$N) ==="
IMPORTANCE_TSV="$OUT/token_importance_n${N}.tsv"
"$PYTHON_BIN" scripts/token_importance.py \
  --run_dir "$MODEL_DIR" \
  --valid_set_list "$VALID_LIST" \
  --n_samples "$N" --batch_size "$BS" --move_min_m "$MOVE_MIN_M" --device "$DEVICE" \
  --out_tsv "$IMPORTANCE_TSV" 2>&1 | tee "$OUT/token_importance_n${N}.log"

echo "=== [2/3] attention analysis (PyTorch, $DEVICE, n=$N) ==="
ATTENTION_JSON="$OUT/attention_n${N}.json"
"$PYTHON_BIN" scripts/attention_analysis.py \
  --run_dir "$MODEL_DIR" \
  --valid_set_list "$VALID_LIST" \
  --n_samples "$N" --batch_size "$BS" \
  --move_min_m "$MOVE_MIN_M" --turn_deg "$TURN_DEG" --device "$DEVICE" \
  --out_json "$ATTENTION_JSON" \
  2>&1 | tee "$OUT/attention_analysis_n${N}.log"

echo "=== [3/3] execute notebook and build portable HTML ==="
EXECUTED_NOTEBOOK="$OUT/token_analysis_n${N}.executed.ipynb"
REPORT_HTML="$OUT/token_analysis_n${N}.html"
KERNEL_PREFIX="$OUT/.jupyter-kernel"
KERNEL_NAME="diffusion-planner-token-report"

"$PYTHON_BIN" -m ipykernel install \
  --prefix "$KERNEL_PREFIX" \
  --name "$KERNEL_NAME" \
  --display-name "Diffusion Planner token report" >/dev/null

export TOKEN_IMPORTANCE_TSV="$IMPORTANCE_TSV"
export TOKEN_ATTENTION_JSON="$ATTENTION_JSON"
export TOKEN_REPORT_MODEL_DIR="$MODEL_DIR"
export TOKEN_REPORT_VALID_LIST="$VALID_LIST"
export TOKEN_REPORT_N_SAMPLES="$N"
export TOKEN_REPORT_BATCH_SIZE="$BS"
export TOKEN_REPORT_DEVICE="$DEVICE"
export TOKEN_REPORT_MOVE_MIN_M="$MOVE_MIN_M"
export TOKEN_REPORT_TURN_DEG="$TURN_DEG"
export JUPYTER_PATH="$KERNEL_PREFIX/share/jupyter${JUPYTER_PATH:+:$JUPYTER_PATH}"

"$PYTHON_BIN" -m jupyter nbconvert \
  --execute \
  --to notebook \
  --ExecutePreprocessor.kernel_name="$KERNEL_NAME" \
  --ExecutePreprocessor.timeout=1200 \
  --output "$(basename "$EXECUTED_NOTEBOOK")" \
  --output-dir "$(dirname "$EXECUTED_NOTEBOOK")" \
  "$REPO_ROOT/notebook/token_analysis.ipynb"

"$PYTHON_BIN" -m jupyter nbconvert \
  --to html \
  --template-file "$REPO_ROOT/notebook/portable_html.j2" \
  --HTMLExporter.embed_images=True \
  --output "$(basename "$REPORT_HTML")" \
  --output-dir "$(dirname "$REPORT_HTML")" \
  "$EXECUTED_NOTEBOOK"

echo "done"
echo "  executed notebook: $EXECUTED_NOTEBOOK"
echo "  portable HTML:     $REPORT_HTML"
