lr_scheduler: cosine
learning_rate: ${optimizer.learning_rate}
warmup_steps: 1000
warmup_lr: 1.0e-7
warmup_prefix: true
min_lr: 1.0e-6
decay_steps: 10000
decay_milestones: [20000, 40000]
decay_rate: 0.1
cycle_mul: 1.0
cycle_decay: 0.5
cycle_limit: 1
k_decay: 1.0
